---
esphome:
  name: marantz

rp2040:
  board: rpipicow
  framework:
    # Required until https://github.com/platformio/platform-raspberrypi/pull/36 is merged
    platform_version: https://github.com/maxgerhardt/platform-raspberrypi.git

# Enable logging
logger:
  level: DEBUG
  baud_rate: 0 # Disable logging over uart

# Enable Home Assistant API
api:
  encryption:
    key: !secret marantz_api_encryption

ota:
  safe_mode: True
  password: !secret marantz_ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: True

  # Enable fallback hotspot in case wifi connection fails
  ap:
    ssid: !secret marantz_ap_ssid
    password: !secret marantz_ap_password

output:
  - platform: gpio
    pin:
      number: 32
      mode: OUTPUT
    id: LED

# RS232 UART Config

uart:
  tx_pin: 4
  rx_pin: 5
  baud_rate: 9600
  data_bits: 8
  parity: NONE
  stop_bits: 1
  id: RS232
  debug:
    direction: BOTH
    dummy_receiver: False
    after:
      delimiter: [0x0D]
    sequence:
      - lambda: UARTDebug::log_hex(direction, bytes, ',');

# RS232 Controls

switch:

  # Power Control
  - platform: template
    name: "Power"
    id: power
    icon: 'mdi:power'
    optimistic: True
    turn_on_action:
      - output.turn_on: LED
      # Repeat to ensure that message is read properly
      - repeat:
          count: 2
          then:
            - uart.write:
                id: RS232
                data: [0x40, 0x31, 0x41, 0x31, 0x0D] # @1 A1 \n
            - delay: 0.25s
      - output.turn_off: LED
    turn_off_action:
      - output.turn_on: LED
      # Repeat to ensure that message is read properly
      - repeat:
          count: 2
          then:
            - uart.write:
                id: RS232
                data: [0x40, 0x31, 0x41, 0x32, 0x0D] # @1 A2 \n
            - delay: 0.25s
      - output.turn_off: LED

button:

  # Volume Up
  - platform: template
    name: "Volume Up"
    id: volume_up
    icon: 'mdi:volume-plus'
    on_press:
      - output.turn_on: LED
      - uart.write:
          id: RS232
          data: [0x40, 0x31, 0x47, 0x30, 0x0D] # @1 G0 \n
      - delay: 0.25s
      - output.turn_off: LED

  # Volume Down
  - platform: template
    name: "Volume Down"
    id: volume_down
    icon: 'mdi:volume-minus'
    on_press:
      - output.turn_on: LED
      - uart.write:
          id: RS232
          data: [0x40, 0x31, 0x47, 0x31, 0x0D] # @1 G1 \n
      - delay: 0.25s
      - output.turn_off: LED
